// French locale catalog for English source messages.
export const designerFr: Record<string, string> = {
  "Simulated clock": "Horloge simulée",
  "Start (YYYY-MM-DDTHH:MM)": "Départ (AAAA-MM-JJTHH:MM)",
  "Speed (clock seconds per second)":
    "Vitesse (secondes d'horloge par seconde)",
  "Remove the clock": "Supprimer l'horloge",
  "Clock masters, time switches, and time windows need a simulated clock.":
    "Les horloges maîtresses, programmateurs et plages horaires ont besoin d'une horloge simulée.",
  "Add a simulated clock": "Ajouter une horloge simulée",
  "Clock master": "Horloge maîtresse",
  "Sends the time (10.001) and the date (11.001) of the simulated clock on two new addresses; adds a clock to the scenario if it has none.":
    "Émet l'heure (10.001) et la date (11.001) de l'horloge simulée sur deux nouvelles adresses ; ajoute une horloge au scénario s'il n'en a pas.",
  "Weekly time switch": "Programmateur hebdomadaire",
  "Sends 1 at 07:00 and 0 at 22:00 every day on a new address; edit the program and link the output.":
    "Émet 1 à 07:00 et 0 à 22:00 chaque jour sur une nouvelle adresse ; modifiez le programme et associez la sortie.",
  "Programmed output": "Sortie programmée",
  "Air quality sensor": "Capteur de qualité d'air",
  "Temperature (9.001), humidity (9.007), and CO₂ (9.008) entered on the device; CO₂ alarm (1.005) and ventilation control value (5.001) on new addresses.":
    "Température (9.001), humidité (9.007) et CO₂ (9.008) saisis sur l'appareil ; alarme CO₂ (1.005) et valeur de commande de ventilation (5.001) sur de nouvelles adresses.",
  "Temperature (°C)": "Température (°C)",
  "Humidity (%)": "Humidité (%)",
  "CO₂ (ppm)": "CO₂ (ppm)",
  "line {0} has no extension": "la ligne {0} n'a pas d'extension",
  "“{0}” is not an individual address of line {1}":
    "« {0} » n'est pas une adresse individuelle de la ligne {1}",
  "Line extension": "Extension de ligne",
  "Line repeater": "Répéteur de ligne",
  "Extension address": "Adresse de l'extension",
  "The extension connects a second segment to the main segment of the line. Place devices behind it from their own form. A line has at most one extension in this model; real installations allow up to three repeaters, each connected to the main segment, never in series.":
    "L'extension relie un second segment au segment principal de la ligne. Placez des appareils derrière elle depuis leur propre fiche. Ce modèle admet une seule extension par ligne ; une installation réelle admet jusqu'à trois répéteurs, chacun relié au segment principal, jamais en série.",
  "Add a line repeater or a segment coupler to show a second segment on this line.":
    "Ajoutez un répéteur de ligne ou un coupleur de segment pour montrer un second segment sur cette ligne.",
  Segment: "Segment",
  "On the segment behind the line extension ({0})":
    "Sur le segment derrière l'extension de ligne ({0})",
  "Weather station": "Station météo",
  "Wind speed (9.005) and brightness (9.004) entered on the device, wind alarm (1.005) and sun protection (1.001) outputs on four new addresses.":
    "Vitesse du vent (9.005) et luminosité (9.004) saisies sur l'appareil, sorties alarme vent (1.005) et protection solaire (1.001) sur quatre nouvelles adresses.",
  "Wind (m/s)": "Vent (m/s)",
  "Brightness (lx)": "Luminosité (lx)",
  "Logic module": "Module logique",
  "AND of two one-bit inputs sent on a new output address; change the operation and link the inputs.":
    "ET de deux entrées 1 bit émis sur une nouvelle adresse de sortie ; changez l'opération et associez les entrées.",
  "Logic input 1": "Entrée logique 1",
  "Logic input 2": "Entrée logique 2",
  channel: "canal",
  object: "objet",
  required: "requis",
  Documentation: "Documentation",
  Designer: "Concepteur",
  "BusDiagram designer": "Concepteur BusDiagram",
  "Start from a template": "Partir d'un modèle",
  "Start from a template…": "Partir d'un modèle…",
  "Insert a device": "Insérer un participant",
  "+ Insert…": "+ Insérer…",
  "Line to insert on": "Ligne où insérer",
  "on line {0}": "sur la ligne {0}",
  Format: "Mettre en forme",
  "Reformat the JSON": "Remettre en forme le JSON",
  "Open…": "Ouvrir…",
  "Open a .json file": "Ouvrir un fichier .json",
  "→ Format 2": "→ Format 2",
  "Convert a format 1 scenario to format 2":
    "Convertir un scénario de format 1 au format 2",
  Export: "Exporter",
  "Extensions…": "Extensions…",
  "Extension {0} rejected: {1}": "Extension {0} refusée : {1}",
  "Extension {0} loaded.": "Extension {0} chargée.",
  "Note: the player does not load extensions; prefer the standalone page.":
    "Attention : le lecteur ne charge pas les extensions ; préférez la page autonome.",
  "Code to paste into a page…": "Code à coller dans une page…",
  "Standalone page (.html)": "Page autonome (.html)",
  "JSON file": "Fichier JSON",
  "Player link…": "Lien de lecture…",
  "bus-diagram.js library": "Bibliothèque bus-diagram.js",
  Language: "Langue",
  Help: "Aide",
  Guided: "Guidé",
  "JSON scenario": "Scénario JSON",
  "Ctrl+Space: suggestions (fields, ports, DPTs, declared group addresses, objects and channels of the device).":
    "Ctrl+Espace : suggestions (champs, ports, DPT, adresses de groupe déclarées, objets et canaux du participant).",
  Toolbar: "Barre",
  full: "complète",
  compact: "compacte",
  none: "aucune",
  Monitor: "Moniteur",
  Description: "Description",
  "16:9 slide": "Diapositive 16:9",
  Open: "Ouvrir",
  Copy: "Copier",
  Close: "Fermer",
  "New installation": "Nouvelle installation",
  "Lab kit": "Maquette",
  "Empty installation": "Installation vide",
  "Invalid JSON: {0}": "JSON invalide : {0}",
  "{0}: change rejected — {1}{2}.": "{0} : modification refusée — {1}{2}.",
  "Valid scenario — preview up to date": "Scénario valide — aperçu à jour",
  "{0} errors — the preview shows the last valid version":
    "{0} erreurs — l'aperçu montre la dernière version valide",
  "1 error — the preview shows the last valid version":
    "1 erreur — l'aperçu montre la dernière version valide",
  "(root)": "(racine)",
  "Go to the error": "Aller à l'endroit de l'erreur",
  Insertion: "Insertion",
  "{0} added. {1}": "{0} ajouté. {1}",
  "Fix the JSON syntax before formatting.":
    "Syntaxe JSON à corriger avant la mise en forme.",
  "The scenario must be valid to be converted.":
    "Le scénario doit être valide pour être converti.",
  "Converted to format 2 (default values omitted).":
    "Converti au format 2 (valeurs par défaut omises).",
  "The scenario contains errors: fix them before exporting.":
    "Le scénario contient des erreurs : corrigez-les avant d'exporter.",
  "Copied to the clipboard.": "Copié dans le presse-papiers.",
  "Selected: press Ctrl+C to copy.": "Sélectionné : Ctrl+C pour copier.",
  "Code to paste into the page": "Code à coller dans la page",
  "Once per page, preferably in <head>:":
    "Une fois par page, de préférence dans <head> :",
  'HTML page, Markdown (Hugo, Pandoc), reveal.js slide: paste the code. The first tag loads version {0} of the library from a CDN; this exact version stays available and does not change. To work offline, download bus-diagram.js from the Export menu, place it next to the page, and use <script src="bus-diagram.js"></script> instead. The interface language follows the page\'s lang attribute.':
    "Page HTML, Markdown (Hugo, Pandoc), diapositive reveal.js : collez le code. La première balise charge la version {0} de la bibliothèque depuis un CDN ; cette version exacte reste disponible et ne change pas. Pour travailler hors ligne, téléchargez bus-diagram.js (menu Exporter), placez-le à côté de la page et utilisez <script src=\"bus-diagram.js\"></script> à la place. La langue de l'interface suit l'attribut lang de la page.",
  "Player link": "Lien de lecture",
  "The scenario is stored in the link itself (nothing is sent to a server). Use it in an iframe or presentation software that displays web pages, once the documentation is published.":
    "Le scénario est contenu dans le lien lui-même (rien n'est envoyé sur un serveur). Utilisez-le dans une iframe ou un logiciel de présentation qui affiche des pages web, une fois la documentation publiée.",
  "the root must be an object { … }": "la racine doit être un objet { … }",
  "“{0}” must be a list [ … ]": "« {0} » doit être une liste [ … ]",
  "“ipRouter” must be an object": "« ipRouter » doit être un objet",
  "each line needs an “area.line” address":
    "chaque ligne doit avoir une adresse « zone.ligne »",
  "each device must be an object": "chaque participant doit être un objet",
  "line {0} is not declared": "la ligne {0} n'est pas déclarée",
  "no free address left on line {0}":
    "plus aucune adresse libre sur la ligne {0}",
  "no free group address left in {0}/{1}/…":
    "plus aucune adresse de groupe libre dans {0}/{1}/…",
  "{0}-key push button": "Poussoir {0} touches",
  "One object and one group address per key, toggle with LED.":
    "Un objet et une adresse de groupe par touche, télérupteur avec voyant.",
  "Lighting key {0}": "Éclairage BP{0}",
  "{0}-output switch actuator": "Commutateur {0} sorties",
  "One channel and one lamp per output; fill in the objects' group addresses.":
    "Un canal et une lampe par sortie ; renseigner les adresses de groupe des objets.",
  "Channel {0}": "Canal {0}",
  "Shutter actuator": "Actionneur de volet",
  "Up/down, stop/step, setpoint and position feedback on four new addresses.":
    "Montée/descente, arrêt/pas, consigne et retour de position sur quatre nouvelles adresses.",
  "Shutter up/down": "Volet montée/descente",
  "Shutter stop/step": "Volet arrêt/pas",
  "Requested position": "Position demandée",
  Shutter: "Volet",
  "Presence detector": "Détecteur de présence",
  "A “Passage” key: 1 on detection, 0 after the hold time (10 s), on a new address.":
    "Une touche « Passage » : 1 à la détection, 0 après la temporisation (10 s), sur une nouvelle adresse.",
  Presence: "Présence",
  Passage: "Passage",
  "IP supervisor": "Superviseur IP",
  Supervisor: "Superviseur",
  "Group address": "Adresse de groupe",
  "Declares the next free address 1/1/x (name and DPT to fill in).":
    "Déclare la prochaine adresse libre 1/1/x (nom et DPT à compléter).",
  Line: "Ligne",
  "Adds the next line of the area: couplers and main line appear.":
    "Ajoute la ligne suivante de la zone : coupleurs et ligne principale apparaissent.",
  "area {0} already has its 15 lines": "la zone {0} a déjà ses 15 lignes",
  "Line {0}.{1}": "Ligne {0}.{1}",
  "New function": "Nouvelle fonction",
  "device “{0}” not found": "participant « {0} » introuvable",
  "address {0} not declared": "adresse {0} non déclarée",
  "“{0}” is not a valid group address (e.g. 1/1/1)":
    "« {0} » n'est pas une adresse de groupe valide (ex. 1/1/1)",
  "address {0} is already used": "l'adresse {0} est déjà utilisée",
  "{0} is the sending address of a key of {1}: change that key's address first":
    "{0} est l'adresse d'émission d'une touche de {1} : changez d'abord l'adresse de cette touche",
  "“{0}” is not an individual address (e.g. 1.1.10)":
    "« {0} » n'est pas une adresse individuelle (ex. 1.1.10)",
  Lighting: "Éclairage",
  toggle: "bascule (télérupteur)",
  "Shutter: up/down": "Volet : montée/descente",
  up: "monter",
  down: "descendre",
  "reverse direction": "inverser le sens",
  "Shutter: stop/step": "Volet : arrêt/pas",
  "stop / step ▲": "arrêt / pas ▲",
  "stop / step ▼": "arrêt / pas ▼",
  Scene: "Scène",
  "scene {0}": "scène {0}",
  "0 %": "0 %",
  "25 %": "25 %",
  "50 %": "50 %",
  "75 %": "75 %",
  "100 %": "100 %",
  "force off": "forcer à l'arrêt",
  "force on": "forcer en marche",
  "end of forcing": "fin du forçage",
  "key “{0}” not found": "touche « {0} » introuvable",
  " short": " court",
  " long": " long",
  "the key has no “{0}” gesture": "la touche n'a pas de geste « {0} »",
  "“toggle” only exists for 1-bit data":
    "« bascule » n'existe que pour une donnée 1 bit",
  "{0} carries a {1}, incompatible with the action ({2})":
    "{0} transporte un {1}, incompatible avec l'action ({2})",
  "channel “{0}” not found": "canal « {0} » introuvable",
  "{0} carries a {1}, incompatible with {2}":
    "{0} transporte un {1}, incompatible avec {2}",
  "no equipment connected to this channel":
    "aucun équipement raccordé à ce canal",
  "“{0}”: write scene=value, e.g. 1=1, 2=0":
    "« {0} » : écrire scène=valeur, ex. 1=1, 2=0",
  "{0} is already displayed": "{0} est déjà affichée",
  "object “{0}” not found": "objet « {0} » introuvable",
  "object used by a key: delete or change the key first":
    "objet utilisé par une touche : supprimez ou modifiez d'abord la touche",
  "object used by an LED": "objet utilisé par un voyant",
  "The JSON has a syntax error: fix it in the JSON tab (errors are listed below) to resume guided editing.":
    "Le JSON contient une erreur de syntaxe : corrigez-la dans l'onglet JSON (les erreurs sont listées dessous) pour reprendre l'édition guidée.",
  "This scenario uses format 1. The guided designer works on format 2:":
    "Ce scénario est au format 1. Le concepteur guidé travaille sur le format 2 :",
  "Convert to format 2": "Convertir au format 2",
  "Undo (Ctrl+Z)": "Annuler (Ctrl+Z)",
  Undo: "Annuler",
  "Redo (Ctrl+Y)": "Rétablir (Ctrl+Y)",
  Redo: "Rétablir",
  Installation: "Installation",
  Title: "Titre",
  Instructions: "Consigne",
  "Line name": "Nom de ligne",
  "Adding a device": "Ajout de participant",
  "Add a device…": "Ajouter un participant…",
  "Loaded extensions": "Extensions chargées",
  Name: "Nom",
  "Individual address": "Adresse individuelle",
  Address: "Adresse",
  "Behavior not loaded in the designer: data kept, limited forms.":
    "Comportement non chargé dans le concepteur : données conservées, formulaires limités.",
  "Device settings": "Réglages du participant",
  Setting: "Réglage",
  Deletion: "Suppression",
  "Delete device": "Supprimer le participant",
  Press: "Appui",
  "Short press": "Appui court",
  "Long press": "Appui long",
  Keys: "Touches",
  Label: "Libellé",
  Gesture: "Geste",
  "single press": "appui simple",
  "short press + long press": "appui court + appui long",
  Function: "Fonction",
  "Sending address": "Adresse d'émission",
  LED: "Voyant",
  "Status {0}": "Retour état {0}",
  "Delete key": "Supprimer la touche",
  Key: "Touche",
  "Add a key": "Ajouter une touche",
  "Displayed values": "Valeurs affichées",
  Remove: "Retirer",
  Removal: "Retrait",
  Outputs: "Sorties",
  "none (unused output)": "aucune (sortie libre)",
  "Scenes (number=value, e.g. 1=1, 2=0)":
    "Scènes (numéro=valeur, ex. 1=1, 2=0)",
  Scenes: "Scènes",
  "Delete output": "Supprimer la sortie",
  "Add an output": "Ajouter une sortie",
  "Objects shared by all outputs": "Objets communs à toutes les sorties",
  Port: "Port",
  "Delete object": "Supprimer l'objet",
  "Group addresses": "Adresses de groupe",
  DPT: "DPT",
  "New group address": "Nouvelle adresse de groupe",
  "— none —": "— aucune —",
  "new address": "nouvelle adresse",
  "Advanced settings": "Réglages avancés",
  "behavior “{0}” not loaded": "comportement « {0} » non chargé",
  "{0} links objects of another size: choose a DPT of the same size, or change the objects first":
    "{0} relie des objets d'une autre taille : choisissez un DPT de même taille, ou changez d'abord les objets",
  "line {0} not found": "ligne {0} introuvable",
  "an installation keeps at least one line":
    "une installation garde au moins une ligne",
  "Change rejected": "Modification refusée",
  "Nothing was changed: the form shows the current scenario again.":
    "Rien n'a été modifié : le formulaire montre de nouveau le scénario actuel.",
  "Title and instructions": "Titre et consigne",
  "Instructions shown above the diagram":
    "Consigne affichée au-dessus du schéma",
  "Name of line {0}": "Nom de la ligne {0}",
  "line name": "nom de la ligne",
  "Delete line": "Supprimer la ligne",
  "Delete the line and its {0} devices?":
    "Supprimer la ligne et ses {0} participants ?",
  "Delete the line and its device?": "Supprimer la ligne et son participant ?",
  "Delete the line?": "Supprimer la ligne ?",
  "Deleting line {0}": "Suppression de la ligne {0}",
  "An installation keeps at least one line: add another one before deleting this one.":
    "Une installation garde au moins une ligne : ajoutez-en une autre avant de supprimer celle-ci.",
  "New line": "Nouvelle ligne",
  "No device on this line.": "Aucun participant sur cette ligne.",
  "Add a device on line {0}": "Ajouter un participant sur la ligne {0}",
  "nobody sends": "personne n'émet",
  "nobody listens": "personne n'écoute",
  "No group address.": "Aucune adresse de groupe.",
  "New group address…": "Nouvelle adresse de groupe…",
  "Help text (shown in the diagram inspector)":
    "Texte d'aide (affiché dans l'inspecteur du diagramme)",
  "Help text": "Texte d'aide",
  "Delete “{0}”? Its group addresses remain declared.":
    "Supprimer « {0} » ? Ses adresses de groupe restent déclarées.",
  "Push-button · 1 key": "Poussoir · 1 touche",
  "Push-button · {0} keys": "Poussoir · {0} touches",
  "Switch actuator · 1 output": "Commutateur · 1 sortie",
  "Switch actuator · {0} outputs": "Commutateur · {0} sorties",
  "Shutter actuator · 1 output": "Actionneur de volet · 1 sortie",
  "Shutter actuator · {0} outputs": "Actionneur de volet · {0} sorties",
  Display: "Afficheur",
  "Device without logic": "Participant sans logique",
  "Extension {0}": "Extension {0}",
  "Value sent": "Valeur envoyée",
  "Status feedback listened to (LED)": "Retour d'état écouté (voyant)",
  "Delete key {0}?": "Supprimer la touche {0} ?",
  "Display an address": "Afficher une adresse",
  "free output": "sortie libre",
  "no address": "aucune adresse",
  "Connected load": "Charge raccordée",
  "More options": "Plus d'options",
  "Delete output {0} and its objects?":
    "Supprimer la sortie {0} et ses objets ?",
  Addresses: "Adresses",
  "Flag {0}": "Flag {0}",
  "Deleting the object": "Suppression de l'objet",
  "Data type (DPT)": "Type de donnée (DPT)",
  "Only {0} DPTs are offered: that is the size of the objects linked to this address.":
    "Seuls les DPT de {0} sont proposés : c'est la taille des objets reliés à cette adresse.",
  "Who sends on this address": "Qui émet sur cette adresse",
  "Nobody: no object sends on this address (T flag and first address of the object).":
    "Personne : aucun objet n'émet sur cette adresse (flag T et première adresse de l'objet).",
  "Who listens to this address": "Qui écoute cette adresse",
  "Nobody: no object listens to this address (W flag).":
    "Personne : aucun objet n'écoute cette adresse (flag W).",
  "Delete address": "Supprimer l'adresse",
  "Deleting the address": "Suppression de l'adresse",
  Delete: "Supprimer",
  add: "ajouter",
  sends: "émet",
  listens: "écoute",
  "Remove {0}": "Retirer {0}",
  "1 bit": "1 bit",
  "2 bits": "2 bits",
  "1 byte": "1 octet",
  "fix the JSON syntax first (see the errors)":
    "corrigez d'abord la syntaxe JSON (voir les erreurs)",
  "Display on the IP network; adds the KNXnet/IP routers if missing.":
    "Afficheur sur le réseau IP ; ajoute les routeurs KNXnet/IP s'ils manquent.",
  "the IP routers act as line couplers: the IP network already replaces main lines and backbone":
    "les routeurs IP tiennent lieu de coupleurs de ligne : le réseau IP remplace déjà lignes principales et dorsale",
  "a device is connected to the IP network (supervisor): connect it to a line or delete it first":
    "un participant est raccordé au réseau IP (superviseur) : raccordez-le à une ligne ou supprimez-le d'abord",
  "all 15 areas are already used": "les 15 zones sont déjà utilisées",
  "area {0} not found": "zone {0} introuvable",
  "an installation keeps at least one area":
    "une installation garde au moins une zone",
  "no coupler at {0}": "aucun coupleur en {0}",
  "no IP network: choose KNXnet/IP routers first (Topology)":
    "pas de réseau IP : choisissez d'abord des routeurs KNXnet/IP (Topologie)",
  Topology: "Topologie",
  "Areas, lines and levels of the installation. Click a device — here or in the diagram — to open its sheet.":
    "Zones, lignes et niveaux de l'installation. Cliquez sur un participant — ici ou sur le schéma — pour ouvrir sa fiche.",
  "IP network": "Réseau IP",
  "none (TP installation only)": "aucun (installation TP seule)",
  "KNXnet/IP routers as area couplers (Z.0.0): IP acts as the backbone":
    "routeurs KNXnet/IP en coupleurs de zone (Z.0.0) : l'IP tient lieu de dorsale",
  "KNXnet/IP routers as line couplers (Z.L.0): IP acts as main lines and backbone":
    "routeurs KNXnet/IP en coupleurs de ligne (Z.L.0) : l'IP tient lieu de lignes principales et de dorsale",
  "Always present: the installation has several areas.":
    "Toujours présente : l'installation a plusieurs zones.",
  Backbone: "Dorsale",
  "Backbone 0.0 and area couplers": "Dorsale 0.0 et coupleurs de zone",
  "the IP network acts as it": "le réseau IP en tient lieu",
  "several areas": "plusieurs zones",
  "Always present: several lines per area, or a backbone.":
    "Toujours présentes : plusieurs lignes par zone, ou dorsale.",
  "Main lines": "Lignes principales",
  "Main lines Z.0 and line couplers":
    "Lignes principales Z.0 et coupleurs de ligne",
  "required by the topology": "imposées par la topologie",
  "With routers as line couplers, the IP network replaces main lines and backbone.":
    "Avec des routeurs en coupleurs de ligne, le réseau IP remplace lignes principales et dorsale.",
  "Supervisor on the IP network": "Superviseur sur le réseau IP",
  Area: "Zone",
  "Name of area {0}": "Nom de la zone {0}",
  "area name": "nom de la zone",
  "Area name": "Nom de zone",
  "Delete area": "Supprimer la zone",
  "Delete area {0}, its lines and its {1} device(s)?":
    "Supprimer la zone {0}, ses lignes et ses {1} participant(s) ?",
  "Delete area {0} and its lines?": "Supprimer la zone {0} et ses lignes ?",
  "Deleting area {0}": "Suppression de la zone {0}",
  "Main line": "Ligne principale",
  "New line in area {0}": "Nouvelle ligne dans la zone {0}",
  "Devices outside the topology": "Participants hors topologie",
  "New area": "Nouvelle zone",
  "filter (filter table)": "filtrer (table de filtrage)",
  "route everything": "tout transférer",
  "block everything": "tout bloquer",
  "Couplers and filter tables": "Coupleurs et tables de filtrage",
  "Tables unavailable while the scenario contains errors.":
    "Tables indisponibles tant que le scénario contient des erreurs.",
  "No coupler: a single line, without main line or IP network.":
    "Aucun coupleur : une seule ligne, sans ligne principale ni réseau IP.",
  "As in the project, a coupler's table lists the addresses used on both sides. “Route everything” is for diagnosis, or for a visualization not declared in the project.":
    "Comme dans le projet, la table d'un coupleur liste les adresses utilisées des deux côtés. « Tout transférer » sert au diagnostic, ou à une visualisation non déclarée dans le projet.",
  "Repeater: copies every telegram, without a filter table.":
    "Répéteur : recopie tous les télégrammes, sans table de filtrage.",
  "Filter table": "Table de filtrage",
  "Empty filter table: no address is used on both sides.":
    "Table de filtrage vide : aucune adresse n'est utilisée des deux côtés.",
  "Downwards (primary → secondary line)":
    "Vers le bas (ligne primaire → secondaire)",
  "Upwards (secondary → primary line)":
    "Vers le haut (ligne secondaire → primaire)",
  "Parameter of coupler {0}": "Paramètre du coupleur {0}",
  "IP network (KNXnet/IP routing)": "réseau IP (routage KNXnet/IP)",
  "backbone 0.0": "dorsale 0.0",
  "main line {0}.0": "ligne principale {0}.0",
  "line {0}": "ligne {0}",
  Connection: "Raccordement",
  "What reaches the supervisor": "Ce qui remonte au superviseur",
  "On the IP network, the supervisor receives what the KNXnet/IP routers let through: their filter table decides.":
    "Sur le réseau IP, le superviseur reçoit ce que les routeurs KNXnet/IP laissent passer : leur table de filtrage décide.",
  "Connected to a line through an interface, the supervisor receives what travels on that line: the couplers decide what gets there.":
    "Raccordé à une ligne par une interface, le superviseur reçoit ce qui circule sur cette ligne : les coupleurs décident de ce qui y arrive.",
  "Declaration in the project": "Déclaration dans le projet",
  "Declared in the project (dummy device with its addresses)":
    "Déclaré dans le projet (participant fictif avec ses adresses)",
  "The project knows its addresses: the filter tables let them through to it.":
    "Le projet connaît ses adresses : les tables de filtrage les laissent passer jusqu'à lui.",
  "This supervisor is not declared in the project: couplers block the addresses only it uses. Remedies: declare it (dummy device), or set the couplers to “route everything”.":
    "Ce superviseur n'est pas déclaré dans le projet : les coupleurs bloquent les adresses qu'il est seul à utiliser. Remèdes : le déclarer (participant fictif), ou régler les coupleurs sur « tout transférer ».",
  "USB interface": "Interface USB",
  "W: accepts received writes · T: can send · R: answers reads, on its sending address · U: a received response updates it. C (communication) is always active.":
    "W : accepte les écritures reçues · T : peut émettre · R : répond aux lectures, sur son adresse d'émission · U : une réponse reçue le met à jour. C (communication) est toujours actif.",
  "Communication objects: names and flags":
    "Objets de communication : noms et flags",
  "Name of object {0}": "Nom de l'objet {0}",
  "Object name": "Nom de l'objet",
  "Access to the bus through a USB interface: write and read group addresses from the USB interface panel of the diagram.":
    "Accès au bus par une interface USB : écrire et lire des adresses de groupe depuis le panneau d'interface USB du diagramme.",
  "Dimming (stops on release)": "Variation (arrêt au relâchement)",
  brighter: "plus clair",
  darker: "plus sombre",
  "brighter by 25 %": "plus clair de 25 %",
  "darker by 25 %": "plus sombre de 25 %",
  "Dimmer · 1 output": "Variateur · 1 sortie",
  "Dimmer · {0} outputs": "Variateur · {0} sorties",
  "DALI gateway · 1 group": "Passerelle DALI · 1 groupe",
  "DALI gateway · {0} groups": "Passerelle DALI · {0} groupes",
  switching: "commutation",
  dimming: "variation",
  value: "valeur",
  status: "état",
  "value status": "état valeur",
  fault: "défaut",
  "DALI gateway (2 groups)": "Passerelle DALI (2 groupes)",
  Dimmer: "Variateur",
  "Two DALI groups (ballasts A0–A1 and A2–A3): switching, dimming, value, status and fault per group; fill in the group addresses.":
    "Deux groupes DALI (ballasts A0–A1 et A2–A3) : commutation, variation, valeur, états et défaut par groupe ; renseigner les adresses de groupe.",
  "One dimmable output: switching, dimming, value and status; fill in the group addresses.":
    "Une sortie variable : commutation, variation, valeur et états ; renseigner les adresses de groupe.",
  "Group 1": "Groupe 1",
  "Group 2": "Groupe 2",
  "DALI gateway": "Passerelle DALI",
  "Dimming push-button, 2 keys": "Poussoir variation 2 touches",
  "Short press: on/off; long press: brighter/darker (3.007), stop on release; two new addresses.":
    "Appui court : marche/arrêt ; appui long : plus clair/plus sombre (3.007), arrêt au relâchement ; deux nouvelles adresses.",
  "Lighting switching": "Éclairage commutation",
  "Lighting dimming": "Éclairage variation",
  "Dimming push-button": "Poussoir variation",
  "Key 1 on": "BP1 marche",
  "Key 1 brighter": "BP1 plus clair",
  "Key 2 off": "BP2 arrêt",
  "Key 2 darker": "BP2 plus sombre",
  "4 bits": "4 bits",
  "2 bytes": "2 octets",
  "4 bytes": "4 octets",
  "3 bytes": "3 octets",
  "Room {0}": "Pièce {0}",
  "room {0} not found": "pièce {0} introuvable",
  "the room still feeds {0}: first choose another room for these outputs":
    "la pièce alimente encore {0} : choisir d'abord une autre pièce pour ces sorties",
  "no load connected": "aucune charge raccordée",
  "Rooms (heating)": "Pièces (chauffage)",
  "A room's temperature evolves with its radiators, the outside temperature and its window. Its thermostats and window contacts measure it.":
    "Une pièce a une température qui évolue selon ses radiateurs, la température extérieure et sa fenêtre. Ses thermostats et contacts de fenêtre la mesurent.",
  "{0} °C at start · outside {1} °C": "{0} °C au départ · extérieur {1} °C",
  "Initial temperature (°C)": "Température au départ (°C)",
  "Outside temperature (°C)": "Température extérieure (°C)",
  "Window open at start": "Fenêtre ouverte au départ",
  "Delete room": "Supprimer la pièce",
  "Delete room {0}?": "Supprimer la pièce {0} ?",
  Room: "Pièce",
  "Add a room": "Ajouter une pièce",
  "Room thermostat": "Thermostat d'ambiance",
  "Heating actuator · 1 output": "Actionneur de chauffage · 1 sortie",
  "Heating actuator · {0} outputs": "Actionneur de chauffage · {0} sorties",
  "Window contact": "Contact de fenêtre",
  "Temperature sensor": "Sonde de température",
  "Heated room": "Pièce chauffée",
  "Group objects": "Objets de communication",
  "Room 1": "Pièce 1",
  "PI control of its room: temperature (9.001) and heating control value (5.001) on new addresses; mode (20.102), window and presence to be linked.":
    "Régulation PI de sa pièce : température (9.001) et commande de chauffage (5.001) sur de nouvelles adresses ; mode (20.102), fenêtre et présence à associer.",
  "Heating actuator, 2 outputs": "Actionneur de chauffage 2 sorties",
  "Electrothermal valves driven by PWM from a 5.001 control value; fill in the group addresses.":
    "Vannes thermoélectriques pilotées en PWM depuis une grandeur de commande 5.001 ; renseigner les adresses de groupe.",
  "Heating actuator": "Actionneur de chauffage",
  "H{0} control value": "H{0} grandeur de commande",
  "H{0} control value status": "H{0} état de la commande",
  "Sends its room's window opening (1.019) on a new address, to be linked to the thermostat's “Window” object.":
    "Transmet l'ouverture de la fenêtre de sa pièce (1.019) sur une nouvelle adresse, à associer à l'objet « Fenêtre » du thermostat.",
  "New device": "Nouveau participant",
  "This behaviour requires settings (*): fill them in, then add the device on line {0}.":
    "Ce comportement exige des réglages (*) : renseignez-les, puis ajoutez le participant sur la ligne {0}.",
  "Output settings": "Réglages de la sortie",
  "Load settings": "Réglages de la charge",
  "Add device": "Ajouter le participant",
  "No spontaneous transmission (T flag and object's first address): the address is only read on request.":
    "Aucune émission spontanée (flag T et première adresse de l'objet) : l'adresse n'est lue que sur demande.",
  "Who answers reads (R flag)": "Qui répond aux lectures (flag R)",
  "No object takes writes (W flag); read responses are taken into account below.":
    "Aucun objet ne prend les écritures (flag W) ; les réponses à une lecture sont prises en compte ci-dessous.",
  "Who takes responses (U flag)": "Qui prend les réponses (flag U)",
  "Remove value": "Retirer la valeur",
  "Back to default value ({0})": "Revenir à la valeur par défaut ({0})",
  "Back to default value": "Revenir à la valeur par défaut",
  "view {0}": "vue {0}",
  "No extension loaded.": "Aucune extension chargée.",
  "Replace…": "Remplacer…",
  "Extension {0} removed.": "Extension {0} retirée.",
  "Sends its room's temperature (9.001) on a new address, to link for instance to a thermostat's “External temperature” object.":
    "Émet la température de sa pièce (9.001) sur une nouvelle adresse, à associer par exemple à l'objet « Température externe » d'un thermostat.",
  Extensions: "Extensions",
  "Scripts adding behaviours, equipment or views. They are stored in this browser and embedded in the exported standalone page. A failing script leaves no definition loaded.":
    "Scripts qui ajoutent des comportements, équipements ou vues. Ils sont mémorisés dans ce navigateur et embarqués dans la page autonome exportée. Un script qui échoue ne laisse aucune définition chargée.",
  "Load an extension…": "Charger une extension…",
  "Load, replace or remove extensions (.js)":
    "Charger, remplacer ou retirer des extensions (.js)",
  "Refused: extension {0} would fail ({1}). Nothing was changed.":
    "Refusé : l'extension {0} échouerait ({1}). Rien n'a été modifié.",
  "timed out": "délai dépassé",
  "Output initial state": "État initial de la sortie",
  "Load initial state": "État initial de la charge",
  Yes: "Oui",
  No: "Non",
  "The extensions are embedded in the code: loaded as-is through <script src> tags, they would conflict (global variables with the same name).":
    "Les extensions sont intégrées au code : chargées telles quelles par des balises <script src>, elles entreraient en conflit (variables globales de même nom).",
  "Place the extension files next to the page.":
    "Placez les fichiers des extensions à côté de la page.",
  "{0} ({1}): {2} carries a {3}, incompatible with {4}":
    "{0} ({1}) : {2} transporte un {3}, incompatible avec {4}",
  "{0} is the only address of the key using {1} ({2}): a key must send on an address":
    "{0} est la seule adresse de la touche qui utilise {1} ({2}) : une touche doit émettre sur une adresse",
  "no output selected": "aucune sortie choisie",
  "no setting selected": "aucun réglage choisi",
  "{0} does not have the same behaviour as {1}":
    "{0} n'a pas le même comportement que {1}",
  "Back to: {0}": "Revenir à : {0}",
  Back: "Précédent",
  "Copy settings to…": "Copier les réglages vers…",
  "Open {0} in {1}": "Ouvrir {0} dans {1}",
  "Delete {0} and remove it from {1} object(s) on {2} device(s): {3}?":
    "Supprimer {0} et la retirer de {1} objet(s) sur {2} participant(s) : {3} ?",
  "Delete {0}? No object uses it.": "Supprimer {0} ? Aucun objet ne l'utilise.",
  "Edit linked objects…": "Modifier les objets associés…",
  "Objects linked to {0}": "Objets associés à {0}",
  "Tick the objects that use this address. Adding puts it at the end of the object's list (listened to); it only becomes its sending address if it had none. Flags and other addresses do not change.":
    "Cochez les objets qui utilisent cette adresse. Un ajout la place en fin de liste de l'objet (écoutée) ; elle ne devient son adresse d'émission que s'il n'en avait pas. Flags et autres adresses ne changent pas.",
  "Filter: device, object, output…": "Filtrer : participant, objet, sortie…",
  "{0}: data size differs from {1}":
    "{0} : taille de donnée différente de celle de {1}",
  "Active flags": "Flags actifs",
  sending: "émission",
  Summary: "Bilan",
  "will have no group address": "n'aura plus d'adresse de groupe",
  "{0} becomes its sending address": "{0} devient son adresse d'émission",
  "its sending address becomes {0}": "son adresse d'émission devient {0}",
  "No change.": "Aucun changement.",
  "Links of {0}: {1} added, {2} removed":
    "Associations de {0} : {1} ajout(s), {2} retrait(s)",
  Apply: "Appliquer",
  "Connected load (type, room, settings)":
    "Charge raccordée (type, pièce, réglages)",
  "Copy settings of {0}": "Copier les réglages de {0}",
  "To (same device type) — objects and group addresses of the chosen outputs are not changed:":
    "Vers (même type de participant) — les objets et adresses de groupe des sorties choisies ne sont pas modifiés :",
  "Summary: {0} of {1} → {2}.": "Bilan : {0} de {1} → {2}.",
  "Choose at least one output and one category.":
    "Choisissez au moins une sortie et une catégorie.",
  "Settings of {0} copied to {1} output(s)":
    "Réglages de {0} copiés vers {1} sortie(s)",
  "Show address {0}": "Voir l'adresse {0}",
  "listened to as well; it still sends on {0}":
    "écoutée en plus ; il émet toujours sur {0}",
};
