// Generated from schema/scenario-v2.schema.json by `npm run schema`. Do not edit by hand.

/**
 * KNX device with an individual address, objects, buttons, inputs, and channels.
 */
export type Device = {
/**
 * ID unique within the scenario.
 */
id: string
/**
 * Name shown on the device card; defaults to the ID.
 */
name?: string
/**
 * Individual address in area.line.device form; its line must be declared.
 */
address?: string
/**
 * Device grouping and rendering: pushButton, switchActuator, shutterActuator, sensor, supervisor, generic…
 */
kind: string
/**
 * Versioned ID of the device's registered behavior.
 */
behavior: (("pushButton/v1" | "switchActuator/v1" | "shutterActuator/v1" | "display/v1" | "passive/v1" | "presenceDetector/v1" | "usbInterface/v1" | "dimmerActuator/v1" | "daliGateway/v1" | "roomThermostat/v1" | "heatingActuator/v1" | "windowContact/v1" | "temperatureSensor/v1" | "logicGate/v1" | "weatherStation/v1" | "airQualitySensor/v1" | "clockMaster/v1" | "timeSwitch/v1") | string)
/**
 * Device parameters defined by its behavior.
 */
parameters?: {

}
/**
 * Communication medium: TP by default, or IP on the topology.ip network; supervisors default to IP.
 */
medium?: ("TP" | "IP")
/**
 * Assigned room ID; thermostats, window contacts, and temperature sensors observe that room.
 */
room?: string
/**
 * false: do not include this virtual device in coupler filter tables.
 */
inFilterTables?: boolean
/**
 * Device on the downstream segment of a line extension.
 */
downstream?: boolean
/**
 * Explanation shown when selecting the device card.
 */
description?: string
/**
 * Communication objects in device-card order.
 */
objects: Object[]
/**
 * Keys (push button, sensor).
 */
buttons?: Button[]
/**
 * Numeric inputs.
 */
inputs?: Input[]
/**
 * Actuator channels (outputs).
 */
channels?: Channel[]
}
/**
 * Button drawn on the device card; use press or a short/long pair.
 */
export type Button = (Button1 & {
/**
 * ID unique among buttons and inputs on this device.
 */
id: string
/**
 * Label on the button; for example “Key 2 · Down” displays Key 2 prominently.
 */
label?: string
/**
 * Icon inferred from the action when omitted.
 */
icon?: ("on" | "off" | "toggle" | "up" | "down" | "updown" | "scene" | "presence" | "clock" | "dimUp" | "dimDown")
/**
 * Action taken immediately on press; cannot be combined with short/long.
 */
press?: {
/**
 * ID of an object on the same device (input port, with a group address).
 */
object: string
/**
 * Value within the object's DPT range, or “toggle” to invert a one-bit local object value.
 */
value: (number | "toggle")
}
/**
 * Action on release before the long-press threshold.
 */
short?: {
/**
 * ID of an object on the same device (input port, with a group address).
 */
object: string
/**
 * Value within the object's DPT range, or “toggle” to invert a one-bit local object value.
 */
value: (number | "toggle")
}
/**
 * Action after the long-press threshold (0.5 s by default).
 */
long?: {
/**
 * ID of an object on the same device (input port, with a group address).
 */
object: string
/**
 * Value within the object's DPT range, or “toggle” to invert a one-bit local object value.
 */
value: (number | "toggle")
}
/**
 * Action on release after a long press, such as stopping DPT 3.007 dimming.
 */
release?: {
/**
 * ID of an object on the same device (input port, with a group address).
 */
object: string
/**
 * Value within the object's DPT range, or “toggle” to invert a one-bit local object value.
 */
value: (number | "toggle")
}
/**
 * Object whose value lights the button indicator.
 */
led?: string
})
export type Button1 = {
[k: string]: unknown
}
/**
 * Non-KNX equipment connected to a channel output.
 */
export type Equipment = {
/**
 * Equipment type: lamp, shutter, or a registered extension type.
 */
type: (("lamp" | "shutter" | "dimmableLamp" | "daliGroup" | "radiator" | "fan" | "appliance") | string)
/**
 * View type; defaults to the equipment type, such as an extension's ledStrip view.
 */
view?: string
/**
 * Heated or cooled room ID from rooms; required for a radiator.
 */
room?: string
/**
 * Equipment parameters, such as a shutter's actualTravelTimeMs.
 */
parameters?: {

}
/**
 * Initial physical state, such as a shutter's positionPct.
 */
initialState?: {

}
}

/**
 * BusDiagram scenario, format 2. Generated by `npm run schema`.
 */
export interface ScenarioV2 {
/**
 * Schema path for editor completion; ignored by BusDiagram.
 */
$schema?: string
/**
 * Format version 2. Without this field, the file is read as legacy format 1.
 */
formatVersion: 2
/**
 * Title displayed in the toolbar.
 */
title?: string
/**
 * Description displayed below the toolbar.
 */
description?: string
/**
 * Twisted-pair lines. Multiple lines add line couplers and main lines; multiple areas add a backbone.
 * 
 * @minItems 1
 */
lines: [Line, ...(Line)[]]
/**
 * Simulated clock: local date and time at simulation start, and acceleration. Clock masters, time switches, and time windows use it.
 */
clock?: {
/**
 * Local date and time at start, such as 2026-09-28T21:58:00 (no time zone).
 */
start: string
/**
 * Clock seconds per simulated second; 60 makes one minute pass per second.
 */
speed?: number
}
/**
 * Rooms: thermal state shared by assigned thermostats, window contacts, and radiators.
 */
rooms?: Room[]
/**
 * Topology levels and coupler settings. Without this field, a main line appears with two lines in an area and a backbone with two areas.
 */
topology?: {
/**
 * Backbone line 0.0 and area couplers A.0.0, even with one area.
 */
backbone?: boolean
/**
 * Area main lines A.0 and line couplers A.L.0, even with one line.
 */
mainLines?: boolean
/**
 * IP network: KNXnet/IP routers replace area couplers (areaCouplers, A.0.0) or line couplers (lineCouplers, A.L.0). Devices with medium IP connect to it.
 */
ip?: ("areaCouplers" | "lineCouplers")
/**
 * Area names.
 */
areas?: {
/**
 * Area number.
 */
address: number
/**
 * Area name displayed in the diagram, for example “Building A”.
 */
name?: string
}[]
/**
 * Group-telegram routing settings for couplers and routers; filtering is the default.
 */
couplers?: {
/**
 * Coupler address: A.L.0 for a line or A.0.0 for an area.
 */
address: string
/**
 * Display name.
 */
name?: string
/**
 * Primary-to-secondary direction: filter by association table, route everything, or block everything.
 */
down?: ("filter" | "route" | "block")
/**
 * Secondary → primary line: filter, route, or block.
 */
up?: ("filter" | "route" | "block")
}[]
}
/**
 * Legacy single-router IP network setting; prefer topology.ip. The address must belong to a coupler (A.L.0 or A.0.0).
 */
ipRouter?: {
/**
 * Router individual address.
 */
address: string
/**
 * Display name; defaults to “KNX/IP router”.
 */
name?: string
}
/**
 * Declared group addresses: names and DPTs displayed in the monitor and inherited by associated objects.
 */
groupAddresses?: GroupAddress[]
/**
 * Devices in cable order on their line; order determines propagation delay.
 */
devices: Device[]
/**
 * Initial simulation settings.
 */
options?: {
/**
 * Initial speed (1 = normal simulated time, 0.35 = slower).
 */
speed?: number
/**
 * Show coupler filter tables on startup.
 */
filterTables?: boolean
}
}
/**
 * TP line.
 */
export interface Line {
/**
 * Line address in area.line form, such as 1.1; values 1–15. Main lines and backbone come from topology.
 */
address: string
/**
 * Name displayed under the bus, for example “Example line”.
 */
name?: string
/**
 * Line extension: repeater or segment coupler to a downstream segment.
 */
extension?: {
/**
 * Extension individual address on the line, such as 2.1.64.
 */
address: string
/**
 * repeater: forward without filtering; segmentCoupler: use a filter table.
 */
mode?: ("repeater" | "segmentCoupler")
/**
 * Show a repeater/segment-coupler selector in the toolbar.
 */
switchable?: boolean
}
}
/**
 * Room thermal model: heat loss toward outside temperature plus equipment output; an open window increases loss.
 */
export interface Room {
/**
 * ID referenced by room assignments.
 */
id: string
/**
 * Display name; defaults to the ID.
 */
name?: string
/**
 * Initial indoor temperature in °C; defaults to 20.
 */
temperatureC?: number
/**
 * Outside temperature in °C; defaults to 5.
 */
outsideTemperatureC?: number
/**
 * Window initially open.
 */
windowOpen?: boolean
/**
 * Thermal loss time constant in simulated milliseconds; defaults to 300,000 ms.
 */
timeConstantMs?: number
}
/**
 * Declared group address.
 */
export interface GroupAddress {
/**
 * Three-level group address (main/middle/subgroup), such as 1/1/1.
 */
address: string
/**
 * Purpose shown in the monitor and tooltips.
 */
name?: string
/**
 * DPT inherited by objects that do not declare their own.
 */
dpt?: ("1.001" | "1.002" | "1.003" | "1.005" | "1.007" | "1.008" | "1.009" | "1.010" | "1.011" | "1.012" | "1.017" | "1.018" | "1.019" | "1.100" | "2.001" | "3.007" | "5.001" | "5.010" | "17.001" | "20.102" | "9.001" | "9.002" | "9.004" | "9.005" | "9.007" | "9.008" | "7.600" | "10.001" | "11.001" | "13.010" | "14.056")
}
/**
 * Communication object of a device.
 */
export interface Object {
/**
 * ID unique within the device; buttons, inputs, and indicators may refer to it.
 */
id: string
/**
 * Name shown on the device card; defaults to the ID.
 */
name?: string
/**
 * Associated group addresses: the first is the sending address; others are receive-only. An empty list leaves the object unassociated.
 */
ga: (string | string[])
/**
 * Object DPT; defaults to the DPT of its first declared group address.
 */
dpt?: ("1.001" | "1.002" | "1.003" | "1.005" | "1.007" | "1.008" | "1.009" | "1.010" | "1.011" | "1.012" | "1.017" | "1.018" | "1.019" | "1.100" | "2.001" | "3.007" | "5.001" | "5.010" | "17.001" | "20.102" | "9.001" | "9.002" | "9.004" | "9.005" | "9.007" | "9.008" | "7.600" | "10.001" | "11.001" | "13.010" | "14.056")
/**
 * Object role in the device's behavior.
 */
port: ("input" | "display" | "switch" | "status" | "move" | "stopStep" | "positionCommand" | "positionStatus" | "scene" | "forced" | "dim" | "value" | "valueStatus" | "error" | "broadcastSwitch" | "broadcastValue" | "generalError" | "actualTemp" | "externalTemp" | "baseSetpoint" | "setpointShift" | "setpointStatus" | "hvacMode" | "hvacModeStatus" | "presence" | "window" | "heatCool" | "heatCoolStatus" | "heatingValue" | "heatingSwitch" | "coolingValue" | "coolingSwitch" | "fault" | "contact" | "temperature" | "power" | "energy" | "totalPower" | "powerLimit" | "slatCommand" | "slatStatus" | "windAlarm" | "colourTemperature" | "colourTemperatureStatus" | "logicIn" | "enable" | "time" | "logicOut" | "wind" | "brightness" | "outdoorTemp" | "sunProtection" | "humidity" | "co2" | "co2Alarm" | "humidityAlarm" | "ventilation" | "date" | "output")
/**
 * Channel ID within the device; required by actuator ports.
 */
channel?: string
/**
 * Initial value (zero by default; unknown for a display port).
 */
value?: (number | null)
/**
 * Modeled flags: W write, T transmit, R read, U update. C communication is always enabled.
 */
flags: {
/**
 * Accept a received GroupValueWrite; otherwise the telegram is ignored and the value stays unchanged.
 */
W: boolean
/**
 * Allow the behavior to transmit this object; otherwise its value may change locally without a telegram.
 */
T: boolean
/**
 * Answer GroupValueRead on the object's sending address; enabled by default for status ports.
 */
R?: boolean
/**
 * Apply a received GroupValueResponse as an update; enabled by default for display ports.
 */
U?: boolean
}
}
/**
 * Numeric input drawn on the device card.
 */
export interface Input {
/**
 * ID unique among buttons and inputs on this device.
 */
id: string
/**
 * The only input type is number.
 */
type: "number"
/**
 * Label displayed above the input.
 */
label?: string
/**
 * Input object with a group address; written and transmitted on submission.
 */
object: string
/**
 * Minimum value; defaults to the DPT minimum.
 */
min?: number
/**
 * Maximum value; defaults to the DPT maximum.
 */
max?: number
/**
 * Input step; defaults to 1.
 */
step?: number
}
/**
 * Actuator output channel; declare hardware channels even when unused.
 */
export interface Channel {
/**
 * ID unique within the device and referenced by its communication objects.
 */
id: string
/**
 * Load label, such as L1; use “unused” for an unconnected output.
 */
label?: string
/**
 * Behavior-specific channel parameters, such as timer or travel time.
 */
parameters?: {

}
/**
 * Initial application state of the channel.
 */
initialState?: {

}
/**
 * Connected equipment, or null for a free output without a drawn load.
 */
equipment?: (Equipment | null)
/**
 * Scene presets: scene number 1–64 maps to a relay state or shutter position.
 */
scenes?: {
[k: string]: number
}
}
