// Authoring schema (JSON Schema 2020-12) for format v2, built from definitions
// recorded: the behavior and equipment parameters are integrated.
// It is used for publishing (self-completion, help), reference documentation and testing.
// contract; the validator executed by the engine remains builtScenario(), which applies in addition
// cross-reference rules (objects, channels, ports' DPTs, addresses).
import type { ParamSchema } from "./contracts";
import { SUPPORTED_DPTS, dptInfo } from "./dpt";
import type { Registry } from "./registry";

const BYTE = "([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])";
const NIBBLE = "([0-9]|1[0-5])";
const MAIN = "([0-9]|[12][0-9]|3[01])";

export const IA_PATTERN = `^${NIBBLE}\\.${NIBBLE}\\.${BYTE}$`;
const NIBBLE1 = "([1-9]|1[0-5])";
export const LINE_PATTERN = `^${NIBBLE1}\\.${NIBBLE1}$`;
export const GA_PATTERN = `^${MAIN}/[0-7]/${BYTE}$`;
const ID_PATTERN = "^[A-Za-z][\\w.-]*(/v\\d+)?$";
/** Device IDs, object, channel, key, input: without "/" or space. */
export const ID_ATOM = "^[A-Za-z0-9_][A-Za-z0-9_.-]*$";

const ICONS: [string, string][] = [
  ["on", "I: on"],
  ["off", "O: off"],
  ["toggle", "I/O: toggle"],
  ["up", "▲: up"],
  ["down", "▼: down"],
  ["updown", "▲▼: shutter on one key"],
  ["scene", "☰: scene"],
  ["presence", "◉: presence"],
  ["clock", "◷: clock"],
  ["dimUp", "☼+: brighten"],
  ["dimDown", "☼−: dim"],
  ["heatCool", "☀❄: heating / cooling"],
];

// Enumeration wordings are used for forms; they are not JSON Schema.
const params = (s: ParamSchema | undefined) =>
  s
    ? {
        ...s,
        properties: Object.fromEntries(
          Object.entries(s.properties).map(([k, p]) => {
            const { enumTitles, nullTitle, ...rest } = p;
            void enumTitles;
            void nullTitle;
            return [k, rest];
          }),
        ),
      }
    : { type: "object", maxProperties: 0 };

const text = (description: string) => ({ type: "string", description });

export function buildAuthorSchema(registry: Registry): Record<string, unknown> {
  const behaviorIds = [...registry.behaviors.keys()];
  const equipmentIds = [...registry.equipment.keys()];
  const portOneOf = (
    names: string[],
    describe: (n: string) => string | undefined,
  ) =>
    names.map((n) => ({
      const: n,
      description: describe(n) ?? n,
    }));
  // Every port of the registered behaviors, described by the first one that declares it.
  const portDocs = new Map<string, string | undefined>();
  for (const d of registry.behaviors.values())
    for (const [n, port] of Object.entries(d.ports))
      if (!portDocs.get(n)) portDocs.set(n, port.description);
  const allPorts = [...portDocs.keys()];
  const byBehavior = [...registry.behaviors].map(([id, def]) => ({
    if: { properties: { behavior: { const: id } }, required: ["behavior"] },
    then: {
      properties: {
        parameters: params(def.parameters),
        channels: {
          items: {
            properties: {
              parameters: params(def.channelParameters),
              initialState: params(def.channelInitialState),
            },
          },
        },
        // A device without ports (USB interface) has no objects.
        objects: Object.keys(def.ports).length
          ? {
              items: {
                properties: {
                  port: {
                    oneOf: portOneOf(
                      Object.keys(def.ports),
                      (n) => def.ports[n]?.description,
                    ),
                  },
                },
              },
            }
          : { maxItems: 0 },
      },
    },
  }));
  const byEquipment = [...registry.equipment].map(([id, def]) => ({
    if: { properties: { type: { const: id } }, required: ["type"] },
    then: {
      properties: {
        parameters: params(def.parameters),
        initialState: params(def.initialState),
      },
      ...(def.parameters?.required?.length
        ? { required: ["type", "parameters"] }
        : {}),
    },
  }));
  const action = {
    type: "object",
    description:
      "Button action: write a value to an object on the same device, then transmit it.",
    additionalProperties: false,
    required: ["object", "value"],
    properties: {
      object: text(
        "ID of an object on the same device (input port, with a group address).",
      ),
      value: {
        anyOf: [{ type: "number" }, { const: "toggle" }],
        description:
          "Value within the object's DPT range, or “toggle” to invert a one-bit local object value.",
      },
    },
  };
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: "https://bus-diagram.local/schema/scenario-v2.schema.json",
    title: "ScenarioV2",
    description:
      "BusDiagram scenario, format 2. Generated by `npm run schema`.",
    type: "object",
    additionalProperties: false,
    required: ["formatVersion", "lines", "devices"],
    properties: {
      $schema: text(
        "Schema path for editor completion; ignored by BusDiagram.",
      ),
      formatVersion: {
        const: 2,
        description: "Format version: 2, the only supported version.",
      },
      title: text("Title displayed in the toolbar."),
      description: text("Description displayed below the toolbar."),
      lines: {
        type: "array",
        minItems: 1,
        items: { $ref: "#/$defs/line" },
        description:
          "Twisted-pair lines. Multiple lines add line couplers and main lines; multiple areas add a backbone.",
      },
      clock: {
        type: "object",
        additionalProperties: false,
        required: ["start"],
        description:
          "Simulated clock: local date and time at simulation start, and acceleration. Clock masters, time switches, and time windows use it.",
        properties: {
          start: {
            type: "string",
            pattern: "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}(:\\d{2})?$",
            description:
              "Local date and time at start, such as 2026-09-28T21:58:00 (no time zone).",
          },
          speed: {
            type: "number",
            exclusiveMinimum: 0,
            maximum: 3600,
            default: 1,
            description:
              "Clock seconds per simulated second; 60 makes one minute pass per second.",
          },
        },
      },
      rooms: {
        type: "array",
        items: { $ref: "#/$defs/room" },
        description:
          "Rooms: thermal state shared by assigned thermostats, window contacts, radiators, and fan coils.",
      },
      topology: {
        type: "object",
        description:
          "Topology levels and coupler settings. Without this field, a main line appears with two lines in an area and a backbone with two areas.",
        additionalProperties: false,
        properties: {
          backbone: {
            type: "boolean",
            description:
              "Backbone line 0.0 and area couplers A.0.0, even with one area.",
          },
          mainLines: {
            type: "boolean",
            description:
              "Area main lines A.0 and line couplers A.L.0, even with one line.",
          },
          ip: {
            enum: ["areaCouplers", "lineCouplers"],
            description:
              "IP network: KNXnet/IP routers replace area couplers (areaCouplers, A.0.0) or line couplers (lineCouplers, A.L.0). Devices with medium IP connect to it.",
          },
          areas: {
            type: "array",
            description: "Area names.",
            items: {
              type: "object",
              additionalProperties: false,
              required: ["address"],
              properties: {
                address: {
                  type: "integer",
                  minimum: 1,
                  maximum: 15,
                  description: "Area number.",
                },
                name: text(
                  "Area name displayed in the diagram, for example “Building A”.",
                ),
              },
            },
          },
          couplers: {
            type: "array",
            description:
              "Group-telegram routing settings for couplers and routers; filtering is the default.",
            items: {
              type: "object",
              additionalProperties: false,
              required: ["address"],
              properties: {
                address: {
                  type: "string",
                  pattern: IA_PATTERN,
                  description:
                    "Coupler address: A.L.0 for a line or A.0.0 for an area.",
                },
                name: text("Display name."),
                down: {
                  enum: ["filter", "route", "block"],
                  description:
                    "Primary-to-secondary direction: filter by association table, route everything, or block everything.",
                },
                up: {
                  enum: ["filter", "route", "block"],
                  description:
                    "Secondary → primary line: filter, route, or block.",
                },
              },
            },
          },
        },
      },
      ipRouter: {
        type: "object",
        description:
          "Legacy single-router IP network setting; prefer topology.ip. The address must belong to a coupler (A.L.0 or A.0.0).",
        additionalProperties: false,
        required: ["address"],
        properties: {
          address: {
            type: "string",
            pattern: IA_PATTERN,
            description: "Router individual address.",
          },
          name: text("Display name; defaults to “KNX/IP router”."),
        },
      },
      groupRanges: {
        type: "array",
        description:
          'Names of main groups ("1") and middle groups ("1/2"), shown in the group address tree of the designer.',
        items: {
          type: "object",
          additionalProperties: false,
          required: ["address", "name"],
          properties: {
            address: {
              type: "string",
              pattern: "^([0-9]|[12][0-9]|3[01])(/[0-7])?$",
              description: "Main group (0–31) or middle group (0–31/0–7).",
            },
            name: text("Name of the group, such as Lighting or Dimming."),
          },
        },
      },
      groupAddresses: {
        type: "array",
        items: { $ref: "#/$defs/groupAddress" },
        description:
          "Declared group addresses: names and DPTs displayed in the monitor and inherited by associated objects.",
      },
      devices: {
        type: "array",
        items: { $ref: "#/$defs/device" },
        description:
          "Devices in cable order on their line; order determines propagation delay.",
      },
      options: {
        type: "object",
        description: "Initial simulation settings.",
        additionalProperties: false,
        properties: {
          speed: {
            type: "number",
            exclusiveMinimum: 0,
            description:
              "Initial speed (1 = normal simulated time, 0.35 = slower).",
          },
          filterTables: {
            type: "boolean",
            description: "Show coupler filter tables on startup.",
          },
        },
      },
    },
    $defs: {
      dpt: {
        description:
          "Datapoint type: a simulated DPT, or another standard DPT that passive and display devices show without simulating it.",
        anyOf: [
          {
            oneOf: SUPPORTED_DPTS.map((id) => ({
              const: id,
              description: dptInfo(id)!.name,
            })),
          },
          {
            type: "string",
            pattern: "^\\d{1,3}\\.\\d{3,5}$",
            description:
              "Standard DPT shown but not simulated (passive/v1 and display/v1 objects only): its value stays unknown or raw.",
          },
        ],
      },
      line: {
        type: "object",
        description: "TP line.",
        additionalProperties: false,
        required: ["address"],
        properties: {
          address: {
            type: "string",
            pattern: LINE_PATTERN,
            description:
              "Line address in area.line form, such as 1.1; values 1–15. Main lines and backbone come from topology.",
          },
          name: text(
            "Name displayed under the bus, for example “Example line”.",
          ),
          extension: {
            type: "object",
            description:
              "Line extension: repeater or segment coupler to a downstream segment.",
            additionalProperties: false,
            required: ["address"],
            properties: {
              address: {
                type: "string",
                pattern: IA_PATTERN,
                description:
                  "Extension individual address on the line, such as 2.1.64.",
              },
              mode: {
                enum: ["repeater", "segmentCoupler"],
                description:
                  "repeater: forward without filtering; segmentCoupler: use a filter table.",
              },
              switchable: {
                type: "boolean",
                description:
                  "Show a repeater/segment-coupler selector in the toolbar.",
              },
              powerSupply: {
                $ref: "#/$defs/powerSupply",
                description:
                  "Power supply of the downstream segment; each segment needs its own.",
              },
            },
          },
          powerSupply: {
            $ref: "#/$defs/powerSupply",
            description: "Bus power supply of the line, shown on the diagram.",
          },
        },
      },
      powerSupply: {
        type: "object",
        description:
          "KNX power supply with choke. Shown on the diagram; the bus load is not computed.",
        additionalProperties: false,
        properties: {
          name: text("Name, such as a product reference."),
          currentMa: {
            type: "number",
            exclusiveMinimum: 0,
            description: "Rated current in mA, such as 160, 320, 640, or 1280.",
          },
        },
      },
      groupAddress: {
        type: "object",
        description: "Declared group address.",
        additionalProperties: false,
        required: ["address"],
        properties: {
          address: {
            type: "string",
            pattern: GA_PATTERN,
            description:
              "Three-level group address (main/middle/subgroup), such as 1/1/1.",
          },
          name: text("Purpose shown in the monitor and tooltips."),
          dpt: {
            $ref: "#/$defs/dpt",
            description:
              "DPT inherited by objects that do not declare their own.",
          },
        },
      },
      object: {
        type: "object",
        description: "Communication object of a device.",
        additionalProperties: false,
        required: ["id", "ga", "port", "flags"],
        properties: {
          id: {
            type: "string",
            pattern: ID_ATOM,
            description:
              "ID unique within the device; buttons, inputs, and indicators may refer to it.",
          },
          name: text("Name shown on the device card; defaults to the ID."),
          ga: {
            description:
              "Associated group addresses: the first is the sending address; others are receive-only. An empty list leaves the object unassociated.",
            anyOf: [
              { type: "string", pattern: GA_PATTERN },
              {
                type: "array",
                uniqueItems: true,
                items: { type: "string", pattern: GA_PATTERN },
              },
            ],
          },
          dpt: {
            $ref: "#/$defs/dpt",
            description:
              "Object DPT; defaults to the DPT of its first declared group address.",
          },
          port: {
            oneOf: portOneOf(allPorts, (n) => portDocs.get(n)),
            description: "Object role in the device's behavior.",
          },
          channel: text(
            "Channel ID within the device; required by actuator ports.",
          ),
          value: {
            type: ["number", "null"],
            description:
              "Initial value (zero by default; unknown for a display port).",
          },
          flags: {
            type: "object",
            description:
              "Flags: C communication, R read, W write, T transmit, U update, I read on initialisation.",
            additionalProperties: false,
            required: ["W", "T"],
            properties: {
              W: {
                type: "boolean",
                description:
                  "Accept a received GroupValueWrite; otherwise the telegram is ignored and the value stays unchanged.",
              },
              T: {
                type: "boolean",
                description:
                  "Allow the behavior to transmit this object; otherwise its value may change locally without a telegram.",
              },
              R: {
                type: "boolean",
                description:
                  "Answer a GroupValueRead received on any of the object's addresses, on its sending address; enabled by default for status ports.",
              },
              U: {
                type: "boolean",
                description:
                  "Apply a received GroupValueResponse as an update; enabled by default for display ports.",
              },
              C: {
                type: "boolean",
                description:
                  "Communication (enabled by default): when false, the object neither sends nor handles any message.",
              },
              I: {
                type: "boolean",
                description:
                  "Read on initialisation: when the device starts (start of the simulation, recovery after a bus voltage failure), it reads the object's value on its sending address.",
              },
            },
          },
          priority: {
            enum: ["low", "normal", "urgent"],
            description:
              "Transmission priority of the frames the object sends (low by default); system priority is reserved for management.",
          },
        },
      },
      button: {
        type: "object",
        description:
          "Button drawn on the device card; use press or a short/long pair.",
        additionalProperties: false,
        required: ["id"],
        properties: {
          id: {
            type: "string",
            pattern: ID_ATOM,
            description: "ID unique among buttons and inputs on this device.",
          },
          label: text(
            "Label on the button; for example “Key 2 · Down” displays Key 2 prominently.",
          ),
          icon: {
            oneOf: ICONS.map(([c, d]) => ({ const: c, description: d })),
            description: "Icon inferred from the action when omitted.",
          },
          press: {
            ...action,
            description:
              "Action taken immediately on press; cannot be combined with short/long.",
          },
          short: {
            ...action,
            description: "Action on release before the long-press threshold.",
          },
          long: {
            ...action,
            description:
              "Action after the long-press threshold (0.5 s by default).",
          },
          release: {
            ...action,
            description:
              "Action on release after a long press, such as stopping DPT 3.007 dimming.",
          },
          led: text("Object whose value lights the button indicator."),
        },
        anyOf: [
          { required: ["press"] },
          { required: ["short"] },
          { required: ["long"] },
        ],
        not: {
          anyOf: [
            { required: ["press", "short"] },
            { required: ["press", "long"] },
          ],
        },
      },
      input: {
        type: "object",
        description: "Numeric input drawn on the device card.",
        additionalProperties: false,
        required: ["id", "type", "object"],
        properties: {
          id: {
            type: "string",
            pattern: ID_ATOM,
            description: "ID unique among buttons and inputs on this device.",
          },
          type: {
            const: "number",
            description: "The only input type is number.",
          },
          label: text("Label displayed above the input."),
          object: text(
            "Input object with a group address; written and transmitted on submission.",
          ),
          min: {
            type: "number",
            description: "Minimum value; defaults to the DPT minimum.",
          },
          max: {
            type: "number",
            description: "Maximum value; defaults to the DPT maximum.",
          },
          step: {
            type: "number",
            exclusiveMinimum: 0,
            description: "Input step; defaults to 1.",
          },
        },
      },
      room: {
        type: "object",
        description:
          "Room thermal model: heat loss toward outside temperature plus equipment output; an open window increases loss.",
        additionalProperties: false,
        required: ["id"],
        properties: {
          id: {
            type: "string",
            pattern: ID_ATOM,
            description: "ID referenced by room assignments.",
          },
          name: text("Display name; defaults to the ID."),
          temperatureC: {
            type: "number",
            minimum: -30,
            maximum: 60,
            description: "Initial indoor temperature in °C; defaults to 20.",
          },
          outsideTemperatureC: {
            type: "number",
            minimum: -30,
            maximum: 50,
            description: "Outside temperature in °C; defaults to 5.",
          },
          windowOpen: {
            type: "boolean",
            description: "Window initially open.",
          },
          timeConstantMs: {
            type: "integer",
            minimum: 1000,
            maximum: 86400000,
            description:
              "Thermal loss time constant in simulated milliseconds; defaults to 300,000 ms.",
          },
        },
      },
      equipment: {
        type: "object",
        description: "Non-KNX equipment connected to a channel output.",
        additionalProperties: false,
        required: ["type"],
        properties: {
          type: {
            anyOf: [
              { enum: equipmentIds },
              { type: "string", pattern: ID_PATTERN },
            ],
            description:
              "Equipment type: lamp, shutter, or a registered extension type.",
          },
          name: text(
            "Name of the load, such as “Ceiling light”; shown in the diagram and the designer.",
          ),
          view: text(
            "View type; defaults to the equipment type, such as an extension's ledStrip view.",
          ),
          room: {
            type: "string",
            pattern: ID_ATOM,
            description:
              "Heated or cooled room ID from rooms; required for a radiator, a fan coil, or a heat pump.",
          },
          parameters: {
            type: "object",
            description:
              "Equipment parameters, such as a shutter's actualTravelTimeMs.",
          },
          initialState: {
            type: "object",
            description:
              "Initial physical state, such as a shutter's positionPct.",
          },
        },
        allOf: byEquipment,
      },
      channel: {
        type: "object",
        description:
          "Actuator output channel; declare hardware channels even when unused.",
        additionalProperties: false,
        required: ["id"],
        properties: {
          id: {
            type: "string",
            pattern: ID_ATOM,
            description:
              "ID unique within the device and referenced by its communication objects.",
          },
          label: text(
            "Label of the channel: a load label such as L1 (“unused” for an unconnected output), or the name of an input.",
          ),
          keyLabel: text(
            "Text written on the push-button wired to a contact input (push-button interface), drawn on its key; by default the key shows the label.",
          ),
          keyContact: {
            enum: ["normallyOpen", "normallyClosed"],
            description:
              "Contact of the push-button wired to a contact input: normally open (closes when pressed, default) or normally closed.",
          },
          parameters: {
            type: "object",
            description:
              "Behavior-specific channel parameters, such as timer or travel time.",
          },
          initialState: {
            type: "object",
            description: "Initial application state of the channel.",
          },
          equipment: {
            anyOf: [
              { $ref: "#/$defs/equipment" },
              {
                type: "array",
                items: { $ref: "#/$defs/equipment" },
                description:
                  "Several loads wired in parallel on the output; they all receive its commands.",
              },
              { type: "null" },
            ],
            description:
              "Connected equipment: one load, a list of loads switched together, or null for a free output without a drawn load.",
          },
          scenes: {
            type: "object",
            description:
              "Scene presets: scene number 1–64 maps to a relay state or shutter position.",
            propertyNames: { pattern: "^([1-9]|[1-5][0-9]|6[0-4])$" },
            additionalProperties: { type: "number" },
          },
        },
      },
      device: {
        type: "object",
        description:
          "KNX device with an individual address, objects, buttons, inputs, and channels.",
        additionalProperties: false,
        required: ["id", "kind", "behavior", "objects"],
        properties: {
          id: {
            type: "string",
            pattern: ID_ATOM,
            description: "ID unique within the scenario.",
          },
          name: text("Name shown on the device card; defaults to the ID."),
          address: {
            type: "string",
            pattern: IA_PATTERN,
            description:
              "Individual address in area.line.device form; its line must be declared.",
          },
          kind: text(
            'Type of device, as a free description (buttonInterface, switchActuator, display…). Only a behavior that documents a value gives it an effect: display/v1 draws "supervisor" as a supervision software.',
          ),
          behavior: {
            anyOf: [
              { enum: behaviorIds },
              { type: "string", pattern: ID_PATTERN },
            ],
            description: "Versioned ID of the device's registered behavior.",
          },
          parameters: {
            type: "object",
            description: "Device parameters defined by its behavior.",
          },
          medium: {
            enum: ["TP", "IP"],
            description:
              'Communication medium: TP by default, or IP on the topology.ip network (a supervisor on the IP network writes "IP").',
          },
          room: {
            type: "string",
            pattern: ID_ATOM,
            description:
              "Assigned room ID; thermostats, window contacts, and temperature sensors observe that room.",
          },
          inFilterTables: {
            type: "boolean",
            description:
              "false: do not include this virtual device in coupler filter tables.",
          },
          downstream: {
            type: "boolean",
            description:
              "Device on the downstream segment of a line extension.",
          },
          description: text(
            "Explanation shown when selecting the device card.",
          ),
          objects: {
            type: "array",
            items: { $ref: "#/$defs/object" },
            description: "Communication objects in device-card order.",
          },
          buttons: {
            type: "array",
            items: { $ref: "#/$defs/button" },
            description: "Keys (push button, sensor).",
          },
          inputs: {
            type: "array",
            items: { $ref: "#/$defs/input" },
            description: "Numeric inputs.",
          },
          channels: {
            type: "array",
            items: { $ref: "#/$defs/channel" },
            description: "Actuator channels (outputs).",
          },
        },
        allOf: byBehavior,
      },
    },
  };
}
